feat(*): add dying animation - remaining panic
```
thread 'Compute Task Pool (1)' panicked at 'Attempting to create an EntityCommands for entity 7v1, which doesn't exist.'
```